name: Altguide Check

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout altguide
        uses: actions/checkout@v4
        with:
          repository: 'RoboticsHardwareSolutions/altguide'
          ref: 'main' 
          fetch-depth: 1

      - name: Checkout target
        uses: actions/checkout@v4
        with:
          path: 'target'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r utils/pcb_checker/requirements.txt

      - name: Run altguide script
        run: |
          python utils/pcb_checker/main.py "${{ github.workspace }}/target"